# Generated by Django 5.2.3 on 2025-09-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
