# Generated by Django 5.2.3 on 2025-09-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_seller'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
