# Generated by Django 5.2.3 on 2025-09-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('luggage', 'Luggage'), ('fashion', 'Fashion'), ('books', 'Books'), ('home', 'Home & Kitchen'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('automotive', 'Automotive'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
