# Generated by Django 5.2.3 on 2025-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Shoes', 'Shoes')], max_length=50),
        ),
    ]
