# Generated by Django 5.2.3 on 2025-12-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_orderitem_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
