# Generated by Django 5.2.3 on 2025-12-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bags', 'Bags'), ('Shoes', 'Shoes'), ('Belts', 'Belts'), ('Leather Jackets', 'Leather Jackets'), ('Suit Jackets', 'Suit Jackets')], max_length=50),
        ),
    ]
